In [20]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('datascience_salaries.csv')
df.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [21]:
normalized_df = (df['salary']-df['salary'].min())/(df['salary'].max()-df['salary'].min())

normalized_df.head(100)

0     0.601010
1     0.454545
2     0.191919
3     0.454545
4     0.601010
        ...
95    0.191919
96    0.191919
97    0.191919
98    0.050505
99    0.191919
Name: salary, Length: 100, dtype: float64

In [22]:
cat_cols = ['job_title', 'job_type', 'experience_level', 'location', 'salary_currency']
df_encoded = pd.get_dummies(df.drop(columns=['Unnamed: 0']), columns=cat_cols)
df_encoded.head()

,salary,job_title_Big data,job_title_Data analyst,job_title_Data scientist,job_title_ML Ops,job_title_Machine learning,job_type_Full Time,job_type_Internship,experience_level_Entry,experience_level_Executive,...,location_Wilmington,location_Work from Home,location_Wrocław,location_Zurich,location_tel aviv,location_České Budějovice,location_İstanbul,salary_currency_EUR,salary_currency_GBP,salary_currency_USD
0,149000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,120000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,68000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,120000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,149000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [23]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_encoded)

In [24]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

In [25]:
pca.explained_variance_ratio_

array([0.00850087, 0.00762757])