🌟Exercise 1: Introduction to Data Analysis (Easy)

Data analysis is a process of extracting informations by cleaning and transforming datas from sources of datas.
Enterprises and organisations needs datas analysts to understand/visualise their activities, to eventually manage some issues.

🌟Exercise 2: Dataset Loading and Initial Analysis

In [70]:
import pandas as pd

In [71]:
df1 = pd.read_csv('Mental health Depression disorder Data.csv')
df2 = pd.read_csv('Time Americans Spend Sleeping.csv')
df3 = pd.read_csv('crx.csv')

C:\Users\avigd\AppData\Local\Temp\ipykernel_24932\769445149.py:1: DtypeWarning: Columns (0: Bipolar disorder (%), 1: Eating disorders (%)) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('Mental health Depression disorder Data.csv')

In [72]:
df1.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [73]:
df1.iloc[0]

index                                  0
Entity                       Afghanistan
Code                                 AFG
Year                                1990
Schizophrenia (%)                0.16056
Bipolar disorder (%)            0.697779
Eating disorders (%)            0.101855
Anxiety disorders (%)            4.82883
Drug use disorders (%)          1.677082
Depression (%)                  4.071831
Alcohol use disorders (%)       0.672404
Name: 0, dtype: object

In [74]:
df1.groupby('Entity').describe()

                            index                                      \
                            count          mean           std     min
Entity
Afghanistan                 496.0  32805.314516  29071.284080     0.0
Africa                      244.0  30653.500000  23953.160683  6689.0
Albania                     496.0  33111.862903  29049.144674    28.0
Algeria                     496.0  33310.185484  29035.766784    56.0
American Samoa              196.0  36889.642857  35214.798041    84.0
...                           ...           ...           ...     ...
Western Sub-Saharan Africa  112.0  67369.250000  41270.839226  6328.0
World                       358.0  74310.502793  30743.322068  6356.0
Yemen                       496.0  75350.040323  29044.253278  6384.0
Zambia                      496.0  75548.362903  29057.708162  6412.0
Zimbabwe                    496.0  75746.685484  29071.284080  6440.0

                                                                    \
                                 25%      50%        75%       max
Entity
Afghanistan                  6564.75  30482.5   54400.25  102112.0
Africa                       6749.75  30653.5   54557.25   54618.0
Albania                      6906.75  30824.5   54742.25  102140.0
Algeria                      7126.75  31044.5   54962.25  102168.0
American Samoa               7271.75  31189.5   55107.25  102196.0
...                              ...      ...        ...       ...
Western Sub-Saharan Africa  41666.50  77354.5  103057.25  108440.0
World                       53526.25  77444.0  101361.75  108468.0
Yemen                       53711.75  77629.5  101547.25  108496.0
Zambia                      53931.75  77849.5  101767.25  108524.0
Zimbabwe                    54151.75  78069.5  101987.25  108552.0

                           Anxiety disorders (%)            ...  \
                                           count      mean  ...
Entity                                                      ...
Afghanistan                                 28.0  4.848102  ...
Africa                                       0.0       NaN  ...
Albania                                     28.0  3.368903  ...
Algeria                                     28.0  5.011396  ...
American Samoa                              28.0  3.293312  ...
...                                          ...       ...  ...
Western Sub-Saharan Africa                  28.0  2.878408  ...
World                                       28.0  3.792096  ...
Yemen                                       28.0  4.833025  ...
Zambia                                      28.0  3.560979  ...
Zimbabwe                                    28.0  3.091770  ...

                           Depression (%)           Alcohol use disorders (%)  \
                                      75%       max                     count
Entity
Afghanistan                      4.130865  4.136347                      28.0
Africa                                NaN       NaN                       0.0
Albania                          2.208541  2.223407                      28.0
Algeria                          3.670795  3.732597                      28.0
American Samoa                   2.943256  2.946838                      28.0
...                                   ...       ...                       ...
Western Sub-Saharan Africa       3.781733  3.823984                      28.0
World                            3.541902  3.550852                      28.0
Yemen                            4.017155  4.020945                      28.0
Zambia                           3.595314  3.641811                      28.0
Zimbabwe                         3.107865  3.192789                      28.0

                                                                              \
                                mean       std       min       25%       50%
Entity
Afghanistan                 0.663151  0.004803  0.655686  0.660744  0.662324
Africa                           NaN       NaN       NaN       NaN       NaN
Albania                     1.746757  0.074117  1.654338  1.691166  1.708800
Algeria                     0.653712  0.008320  0.644399  0.646709  0.649574
American Samoa              1.135266  0.010257  1.117152  1.128288  1.137414
...                              ...       ...       ...       ...       ...
Western Sub-Saharan Africa  0.945113  0.015547  0.928563  0.932243  0.936594
World                       1.452807  0.025590  1.396497  1.438480  1.454998
Yemen                       0.631849  0.003297  0.627472  0.629641  0.630551
Zambia                      1.639368  0.010493  1.627975  1.630765  1.633169
Zimbabwe                    1.488051  0.022194  1.447595  1.475451  1.486370


                                 75%       max
Entity
Afghanistan                 0.666597  0.672404
Africa                           NaN       NaN
Albania                     1.838108  1.851517
Algeria                     0.663709  0.665817
American Samoa              1.141638  1.153825
...                              ...       ...
Western Sub-Saharan Africa  0.963420  0.968598
World                       1.468085  1.494452
Yemen                       0.635504  0.636960
Zambia                      1.650236  1.657008
Zimbabwe                    1.511607  1.515641

[276 rows x 40 columns]

In [75]:
df2.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [76]:
df2.iloc[0]

index                                       0
Year                                     2003
Period                                 Annual
Avg hrs per day sleeping                 8.57
Standard Error                          0.018
Type of Days                         All days
Age Group                   15 years and over
Activity                             Sleeping
Sex                                      Both
Name: 0, dtype: object

In [77]:
df2.describe()

            index         Year  Avg hrs per day sleeping  Standard Error
count  945.000000   945.000000                945.000000      945.000000
mean   472.000000  2010.000000                  8.806868        0.086958
std    272.942302     4.322782                  0.545001        0.034631
min      0.000000  2003.000000                  7.720000        0.018000
25%    236.000000  2006.000000                  8.360000        0.063000
50%    472.000000  2010.000000                  8.810000        0.084000
75%    708.000000  2014.000000                  9.190000        0.106000
max    944.000000  2017.000000                 10.650000        0.228000

In [78]:
df3.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [79]:
df3.iloc[0]

b            a
30.83    58.67
0         4.46
u            u
g            g
w            q
v            h
1.25      3.04
t            t
t.1          t
01           6
f            f
g.1          g
00202    00043
0.1        560
+            +
Name: 0, dtype: object

In [80]:
df3.describe()

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

🌟Exercise 3: Identifying Data Types

df1 — Mental health.csv

- index → qualitative: identification of the line, we never do operations on ids
- Entity → qualitative: name of the state
- Code → qualitative
- Year → qualitative but can be quantitative if we want to calculate the difference between two dates
- Schizophrenia, Bipolar disorder, Eating disorders, Anxiety disorders, Drug use disorders, Depression and Alcohol use - disorders → quantitative: they are percentage

df2 — Time Americans Spend Sleeping.csv

- index → qualitative
- Year → qualitative
- Period → qualitative: we don't do operations on this
- Avg hrs per day sleeping → quantitative
- Standard Error → quantitative
- Type of Days → qualitative
- Age Group → qualitative
- Activity → qualitative
- Sex → qualitative

df3 — crx.csv

🌟Exercise 4: Exploring Data Types

In [81]:
irisdf = pd.read_csv('Iris.csv')

In [82]:
irisdf.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [83]:
irisdf.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

irisdf — Iris.csv

- index → qualitative
- PetalWidthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm → quantitative: numerative datas that we can do operations on
- Species → qualitative: the name of the species

🌟Exercise 5: Basic Observation Skills in Data Analysis

In [84]:
df2.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [85]:
df2.groupby('Year').describe()

     index                                                       \
     count   mean         std   min    25%    50%    75%    max
Year
2003  63.0  465.0  274.954542   0.0  232.5  465.0  697.5  930.0
2004  63.0  466.0  274.954542   1.0  233.5  466.0  698.5  931.0
2005  63.0  467.0  274.954542   2.0  234.5  467.0  699.5  932.0
2006  63.0  468.0  274.954542   3.0  235.5  468.0  700.5  933.0
2007  63.0  469.0  274.954542   4.0  236.5  469.0  701.5  934.0
2008  63.0  470.0  274.954542   5.0  237.5  470.0  702.5  935.0
2009  63.0  471.0  274.954542   6.0  238.5  471.0  703.5  936.0
2010  63.0  472.0  274.954542   7.0  239.5  472.0  704.5  937.0
2011  63.0  473.0  274.954542   8.0  240.5  473.0  705.5  938.0
2012  63.0  474.0  274.954542   9.0  241.5  474.0  706.5  939.0
2013  63.0  475.0  274.954542  10.0  242.5  475.0  707.5  940.0
2014  63.0  476.0  274.954542  11.0  243.5  476.0  708.5  941.0
2015  63.0  477.0  274.954542  12.0  244.5  477.0  709.5  942.0
2016  63.0  478.0  274.954542  13.0  245.5  478.0  710.5  943.0
2017  63.0  479.0  274.954542  14.0  246.5  479.0  711.5  944.0

     Avg hrs per day sleeping            ...               Standard Error  \
                        count      mean  ...    75%    max          count
Year                                     ...
2003                     63.0  8.701905  ...  9.130  10.13           63.0
2004                     63.0  8.677778  ...  9.020  10.32           63.0
2005                     63.0  8.745556  ...  9.155   9.96           63.0
2006                     63.0  8.757937  ...  9.140  10.18           63.0
2007                     63.0  8.696667  ...  9.070  10.00           63.0
2008                     63.0  8.731746  ...  9.130  10.13           63.0
2009                     63.0  8.796190  ...  9.195  10.31           63.0
2010                     63.0  8.795397  ...  9.185   9.99           63.0
2011                     63.0  8.832857  ...  9.250  10.15           63.0
2012                     63.0  8.849841  ...  9.205  10.26           63.0
2013                     63.0  8.845397  ...  9.205  10.18           63.0
2014                     63.0  8.902222  ...  9.315  10.32           63.0
2015                     63.0  8.936984  ...  9.350  10.15           63.0
2016                     63.0  8.914444  ...  9.235  10.65           63.0
2017                     63.0  8.918095  ...  9.340  10.50           63.0


          mean       std    min     25%    50%     75%    max
Year
2003  0.063000  0.024183  0.018  0.0490  0.060  0.0755  0.133
2004  0.079873  0.031013  0.026  0.0580  0.076  0.0975  0.157
2005  0.082968  0.031707  0.023  0.0635  0.080  0.1005  0.164
2006  0.086571  0.030602  0.024  0.0690  0.083  0.1055  0.180
2007  0.089540  0.033211  0.024  0.0705  0.088  0.1075  0.182
2008  0.087508  0.034017  0.023  0.0655  0.086  0.1080  0.180
2009  0.083746  0.032968  0.023  0.0645  0.083  0.1030  0.177
2010  0.084270  0.031566  0.024  0.0655  0.081  0.1010  0.159
2011  0.088714  0.034860  0.026  0.0685  0.085  0.1085  0.187
2012  0.088651  0.032459  0.026  0.0690  0.088  0.1045  0.161
2013  0.089778  0.037902  0.027  0.0645  0.086  0.1060  0.228
2014  0.086667  0.032493  0.025  0.0645  0.085  0.1040  0.168
2015  0.097095  0.041316  0.027  0.0715  0.091  0.1200  0.217
2016  0.097270  0.039571  0.028  0.0665  0.093  0.1260  0.189
2017  0.098714  0.036774  0.027  0.0740  0.098  0.1195  0.184

[15 rows x 24 columns]

resume of the datas by year

In [86]:
df2.groupby('Age Group').describe()

                   index                                                 \
                   count   mean         std    min    25%    50%    75%
Age Group
15 to 24 years     135.0  382.0  258.483234   45.0   78.5  382.0  685.5
15 years and over  135.0  337.0  258.483234    0.0   33.5  337.0  640.5
25 to 34 years     135.0  427.0  258.483234   90.0  123.5  427.0  730.5
35 to 44 years     135.0  472.0  258.483234  135.0  168.5  472.0  775.5
45 to 54 years     135.0  517.0  258.483234  180.0  213.5  517.0  820.5
55 to 64 years     135.0  562.0  258.483234  225.0  258.5  562.0  865.5
65 years and over  135.0  607.0  258.483234  270.0  303.5  607.0  910.5

                           Year          ... Avg hrs per day sleeping         \
                     max  count    mean  ...                      75%    max
Age Group                                ...
15 to 24 years     719.0  135.0  2010.0  ...                    9.990  10.65
15 years and over  674.0  135.0  2010.0  ...                    9.280   9.52
25 to 34 years     764.0  135.0  2010.0  ...                    9.365   9.74
35 to 44 years     809.0  135.0  2010.0  ...                    9.140   9.50
45 to 54 years     854.0  135.0  2010.0  ...                    8.950   9.49
55 to 64 years     899.0  135.0  2010.0  ...                    8.860   9.14
65 years and over  944.0  135.0  2010.0  ...                    9.085   9.31

                  Standard Error                                            \
                           count      mean       std    min     25%    50%
Age Group
15 to 24 years             135.0  0.130830  0.033353  0.060  0.1065  0.130
15 years and over          135.0  0.039370  0.009900  0.018  0.0320  0.038
25 to 34 years             135.0  0.098511  0.026718  0.043  0.0790  0.093
35 to 44 years             135.0  0.083126  0.023364  0.042  0.0670  0.080
45 to 54 years             135.0  0.088244  0.024391  0.036  0.0715  0.086
55 to 64 years             135.0  0.088252  0.023199  0.040  0.0725  0.086
65 years and over          135.0  0.080370  0.020711  0.039  0.0665  0.077


                      75%    max
Age Group
15 to 24 years     0.1535  0.228
15 years and over  0.0465  0.061
25 to 34 years     0.1180  0.171
35 to 44 years     0.0990  0.162
45 to 54 years     0.1025  0.151
55 to 64 years     0.1025  0.169
65 years and over  0.0940  0.134

[7 rows x 32 columns]

datas by age group

In [87]:
df2.groupby('Sex').describe()

       index                                                        Year  \
       count   mean        std    min    25%    50%    75%    max  count
Sex
Both   315.0  157.0  91.076891    0.0   78.5  157.0  235.5  314.0  315.0
Men    315.0  472.0  91.076891  315.0  393.5  472.0  550.5  629.0  315.0
Women  315.0  787.0  91.076891  630.0  708.5  787.0  865.5  944.0  315.0

               ... Avg hrs per day sleeping        Standard Error            \
         mean  ...                      75%    max          count      mean
Sex            ...
Both   2010.0  ...                    9.185  10.58          315.0  0.068127
Men    2010.0  ...                    9.140  10.65          315.0  0.103133
Women  2010.0  ...                    9.255  10.52          315.0  0.089613


            std    min     25%    50%     75%    max
Sex
Both   0.024034  0.018  0.0535  0.068  0.0825  0.141
Men    0.036370  0.031  0.0790  0.101  0.1250  0.228
Women  0.032863  0.022  0.0695  0.088  0.1060  0.191

[3 rows x 32 columns]

by gender

🌟 Exercise 6: Identifying Data Types

- A company’s financial reports stored in an Excel file
    → structured
- Photographs uploaded to a social media platform.
    → unstructured
- A collection of news articles on a website.
    → unstructured
- Inventory data in a relational database.
    → structured
- Recorded interviews from a market research study.
    → unstructured

🌟 Exercise 7: Transformation Exercise

- A series of blog posts about travel experiences.
    → analyzing the html and extract datas
- Audio recordings of customer service calls.
    → using a stt program and store it
- Handwritten notes from a brainstorming session.
    → split the text and store it in array
- A video tutorial on cooking.
    → use stt and a llm to structure the datas

🌟 Exercise 8 : Import a file from Kaggle

In [88]:
traindf = pd.read_csv('train.csv')

In [89]:
traindf.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

🌟 Exercise 9 : Export a dataframe to excel format and JSON format.

In [90]:
data = {
    'Name': ['Bob', 'Henry', 'Charles', 'Aurore', 'Alicia', 'Maud'],
    'Age': [28, 34, 29, 32, 31, 35],
    'City': ['New York', 'Paris', 'Berlin', 'London', 'Tokyo', 'Moscow']
}
df = pd.DataFrame(data)
df.to_json('friends.json', orient='records', indent=4)
df.to_csv('friends.csv', index=False)

🌟 Exercise 10: Reading JSON Data

In [91]:
df = pd.read_json('posts.json')

In [93]:
df.head(5)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...